### PR TITLE
chore: sidebar component test

### PR DESCRIPTION
**Pull request by ROak93**
This change is [Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/11)

### CODE REVIEW

**Review by brecke — CHANGES_REQUESTED** [review]
Soo... we just need to remove unnecessary comments and lint the whole thing. Try using the VSCode extension and enable the format on save option and you'll see it working :)

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-:-Lk9qO-uAesdpUv1sdjX:b-1tjf2u)* status: all files reviewed, 11 unresolved discussions (waiting on @RitaOak)

___
*[src/components/crumbs.js, line 2 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9lzip6p9Ga9tpTaMF:-Lk9lzip6p9Ga9tpTaMG:b-b9xwvq) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/crumbs.js#L2)):*
> ```JavaScript
> import { html, LitElement } from 'lit-element';
> //import {PageViewElement} from './page-view-element.js';
> ```

let's remove this if this ain't needed :)
___
*[src/components/dashboard.js, line 6 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9mtY1BK6uRc6p6Ytc:-Lk9mtY1BK6uRc6p6Ytd:b-6veulk) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/dashboard.js#L6)):*
> ```JavaScript
> import './sidebar.js';
> import './top-nav.js';
> //import './crumbs.js';
> ```

same here. No useless comments otherwise we'll soon have lots of those
___
*[src/components/dashboard.js, line 26 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9n4ZW4IXY0jALAxR8:-Lk9n4ZW4IXY0jALAxR9:bo2s5c9) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/dashboard.js#L26)):*
> ```JavaScript
>           <div class="column top-nav">
>             <top-nav></top-nav>
>           </div>
> ```

silly question: isn't it possible to avoid this wrapper div and instead make the <top-nav> have those CSS classes and attributes? Wrapper divs are to be avoided as well, they tend to invade projects bit by bit :)
___
*[src/components/info-cards.js, line 2 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9nV7w7-s7v7SMFR19:-Lk9nV7w7-s7v7SMFR1A:b-7iwvbp) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/info-cards.js#L2)):*
> ```JavaScript
> import { html, LitElement } from 'lit-element';
> //import {PageViewElement} from './page-view-element.js';
> ```

this.
___
*[src/components/info-cards.js, line 46 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9nYwO4B31vsBphvye:-Lk9nYwO4B31vsBphvyf:b-3z8bjc) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/info-cards.js#L46)):*
> ```JavaScript
>       </div>
>     </article>
>   </div>            
> ```

are you using XO and prettier? don't think so. Try downloading the XO plugin to VSCode and it will automatically remove these spaces for you, as well as add proper indentation automatically.

In time, not using XO/prettier properly will also block PRs (as failed tests).
___
*[src/components/my-app.js, line 244 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9o1oq8SvtxPlR_8Me:-Lk9o1oq8SvtxPlR_8Mf:b-b2azte) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/my-app.js#L244)):*
> ```JavaScript
>       </main>
> 
>       
> ```

XO / prettier missing!!
___
*[src/components/sidebar.js, line 2 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9oPTk8cjT5a501vL5:-Lk9oPTk8cjT5a501vL6:bps1s89) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/sidebar.js#L2)):*
> ```JavaScript
> import { html, LitElement } from 'lit-element';
> //import {PageViewElement} from './page-view-element.js';
> ```

here too
___
*[src/components/top-nav.js, line 2 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9p4fH6MAy89JEvBXl:-Lk9p4fH6MAy89JEvBXm:bps1s89) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/top-nav.js#L2)):*
> ```JavaScript
> import { html, LitElement } from 'lit-element';
> //import {PageViewElement} from './page-view-element.js';
> ```

here too
___
*[src/components/top-nav.js, line 93 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9pAWV5LuTyN8w3r30:-Lk9pAWV5LuTyN8w3r31:b-xawjlm) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/top-nav.js#L93)):*
> ```JavaScript
> }
> 
> window.customElements.define('top-nav', topNav);
> ```

it seems to me that this component is too big, don't you think?

I see a lot of markup and that is kind of a code smell: it means that we should split the markup into different components. Which kind of makes sense, because most of that markup will have behaviour anyway, and we wouldn't want to have it all in a single WC, would we?
___
*[style/app.scss, line 16 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9pwkY2U9pdYZOAyGa:-Lk9pwkY2U9pdYZOAyGb:b-7pf4ob) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/style/app.scss#L16)):*
> ```SCSS
> @import "../node_modules/bulma/sass/components/navbar.sass";
> // not working, screws up the page format
> //@import "../node_modules/bulma/sass/components/breadcrumb.sass";
> ```

hmmm?
___
*[style/app.scss, line 31 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9pyZGCL0ZSKT12zjQ:-Lk9pyZGCL0ZSKT12zjR:b-r7a4up) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/style/app.scss#L31)):*
> ```SCSS
> 
> 
> //Should remake the structure in order to include these imports
> ```

why so many comments?

**Comment by ROak93** [comment]
___
*[src/components/dashboard.js, line 26 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9n4ZW4IXY0jALAxR8:-LkP819A4MqY6ewTbQTN:b-rrd7g2) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/dashboard.js#L26)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

silly question: isn't it possible to avoid this wrapper div and instead make the <top-nav> have those CSS classes and attributes? Wrapper divs are to be avoided as well, they tend to invade projects bit by bit :)
</blockquote></details>

Yes and no: we need a specific behaviour for these sections not to get bugged for small screens ^^ Furthermore, the columns are important to keep the <top-nav> in place and create the structure of the page. This is the traditional approach, although we can certainly look at other ways to solve it.

**Comment by ROak93** [comment]
___
*[style/app.scss, line 31 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9pyZGCL0ZSKT12zjQ:-LkPTur8DrmWJb7q49Ma:b-gea22r) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/style/app.scss#L31)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

why so many comments? 
</blockquote></details>

We might need these imports when creating other pages! I removed a few repeated ones but left a those that will probably be used in the future.

**Review by brecke — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-:-LkSpms33jMQ4IRybDe7:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @RitaOak)

___
*[src/components/dashboard.js, line 26 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9n4ZW4IXY0jALAxR8:-LkSpf6XCxnc5cykQ8Nk:b7b6sff) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/dashboard.js#L26)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

Yes and no: we need a specific behaviour for these sections not to get bugged for small screens ^^ Furthermore, the columns are important to keep the <top-nav> in place and create the structure of the page. This is the traditional approach, although we can certainly look at other ways to solve it.
</blockquote></details>

nevermind then :)

**Comment by ROak93** [comment]
___
*[src/components/dashboard.js, line 26 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9n4ZW4IXY0jALAxR8:-LkPdNZLD_2HgiKtP1yF:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/dashboard.js#L26)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

Yes and no: we need a specific behaviour for these sections not to get bugged for small screens ^^ Furthermore, the columns are important to keep the <top-nav> in place and create the structure of the page. This is the traditional approach, although we can certainly look at other ways to solve it.
</blockquote></details>

Done.

**Review by ROak93 — COMMENTED** [review]
> why so many comments?

> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-:-LkP7yMA-i4al4pyYNgZ:b-3j9v7p)* status: all files reviewed, 4 unresolved discussions (waiting on @brecke)

___
*[src/components/crumbs.js, line 2 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9lzip6p9Ga9tpTaMF:-LkOGn9_8TT2Wvn_zYNt:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/crumbs.js#L2)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

let's remove this if this ain't needed :)
</blockquote></details>

Done.
___
*[src/components/dashboard.js, line 6 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9mtY1BK6uRc6p6Ytc:-LkOGsBq5MotD8KNikGF:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/dashboard.js#L6)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

same here. No useless comments otherwise we'll soon have lots of those
</blockquote></details>

Done.
___
*[src/components/info-cards.js, line 2 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9nV7w7-s7v7SMFR19:-LkOY-KG3AO2UXwahWPv:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/info-cards.js#L2)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

this.
</blockquote></details>

Done.
___
*[src/components/info-cards.js, line 46 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9nYwO4B31vsBphvye:-LkOnkBZ5xcX7tgfFJ3W:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/info-cards.js#L46)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

are you using XO and prettier? don't think so. Try downloading the XO plugin to VSCode and it will automatically remove these spaces for you, as well as add proper indentation automatically.

In time, not using XO/prettier properly will also block PRs (as failed tests).
</blockquote></details>

Done.
___
*[src/components/my-app.js, line 244 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9o1oq8SvtxPlR_8Me:-LkOnksr9GloB5dc0uBF:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/my-app.js#L244)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

XO / prettier missing!!
</blockquote></details>

Done.
___
*[src/components/sidebar.js, line 2 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9oPTk8cjT5a501vL5:-LkOmZ6A4Ho4NrrsZqmj:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/sidebar.js#L2)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

here too
</blockquote></details>

Done.
___
*[src/components/top-nav.js, line 2 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9p4fH6MAy89JEvBXl:-LkOmdet9CN8snUnDCgd:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/top-nav.js#L2)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

here too
</blockquote></details>

Done.
___
*[src/components/top-nav.js, line 93 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9pAWV5LuTyN8w3r30:-LkOnnLJ16eELKEged_4:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/src/components/top-nav.js#L93)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

it seems to me that this component is too big, don't you think?

I see a lot of markup and that is kind of a code smell: it means that we should split the markup into different components. Which kind of makes sense, because most of that markup will have behaviour anyway, and we wouldn't want to have it all in a single WC, would we?
</blockquote></details>

Done.
___
*[style/app.scss, line 16 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9pwkY2U9pdYZOAyGa:-LkOn04s7vJmPHNozi-S:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/style/app.scss#L16)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

hmmm?
</blockquote></details>

Done.
___
*[style/app.scss, line 31 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/11#-Lk9pyZGCL0ZSKT12zjQ:-LkPdh_pDwuxaJCLjwHZ:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/0ffb2ae18f84ced95ad32a80920c3c053c30b775/style/app.scss#L31)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

We might need these imports when creating other pages! I removed a few repeated ones but left a those that will probably be used in the future.
</blockquote></details>

Done.

**Review by ROak93 — COMMENTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/11)* status: all files reviewed, 4 unresolved discussions (waiting on @brecke)

**Pull request merged**
