### PR TITLE
New tabs

### PR DESCRIPTION
**Pull request by ROak93**
This change is [Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/3)

### CODE REVIEW

**Review by brecke — CHANGES_REQUESTED** [review]
So...

Apart from the comments below, I suggest also removing the changes from package-lock.json since this should only be updated if and when there are changes to dependencies (as in new versions etc).

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/3#-:-LiJjyQ8A-m0lpoGgXCs:b-fzsz73)* status: all files reviewed, 4 unresolved discussions (waiting on @RitaOak)

___
*[package.json, line 11 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/3#-LiJjbVQBmqEJCwZXqb9:-LiJjbVQBmqEJCwZXqbA:bwoccs4) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/13610f1a297a72fc399dfd98b8dc726839489958/package.json#L11)):*
> ```JSON
>   "scripts": {
>     "start": "polymer serve",
>     "start:webpack": "webpack-dev-server --hot --host 0.0.0.0 --open --mode development",
> ```

hmmm I remember when we did this, but I don't think this is doing anything useful. So let's remove it.
___
*[src/components/homepage.js, line 21 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/3#-LiJkp1b1lPCv5E3k2hw:-LiJkp1cBQb2e89uS9C4:b-bcs0pg) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/13610f1a297a72fc399dfd98b8dc726839489958/src/components/homepage.js#L21)):*
> ```JavaScript
>   }
> }
> window.customElements.define('platform-homepage', OAEHomepage);
> ```

this is not a good name for a custom element... think of it this way: if we ever need to export this WC to other app, would this be a good tag?

Naming is hard :)
___
*[src/components/my-app.js, line 230 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/3#-LiJlCqtBtNaQnd9a-Bo:-LiJlCqtBtNaQnd9a-Bp:b-335i80) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/7ed65ce71c12ab6161b77c311b64f07248e706fb/src/components/my-app.js#L230)):*
> ```JavaScript
>         <my-view2 class="page" ?active="${this._page === 'view2'}"></my-view2>
>         <my-view3 class="page" ?active="${this._page === 'view3'}"></my-view3>
>         <my-view404 class="page" ?active="${this._page === 'view404'}"></my-view404>
> ```

there was no need to remove the 404, was there? But I'm not sure it ever worked
___
*[src/components/oae-main.js, line 29 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/3#-LiJm2D28XvZhaHQR4hc:-LiJm2D28XvZhaHQR4hd:b-kbfth) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/13610f1a297a72fc399dfd98b8dc726839489958/src/components/oae-main.js#L29)):*
> ```JavaScript
> 					<h2>This is OAE!!</h2>
> 					<p>
> 						THIS IS A TEST Head back
> ```

is this really necessary? there is no new behaviour as far as I can tell.

**Review by brecke — COMMENTED** [review]
Still waiting for changes such as the homepage WC naming.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/3#-:-LiNfHApCWi1oARPpb6q:b-lno2qs)* status: all files reviewed, 3 unresolved discussions (waiting on @RitaOak)

**Comment by ROak93** [comment]
___
*[src/components/my-app.js, line 230 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/3#-LiJlCqtBtNaQnd9a-Bo:-LiNf_bd4pj3GUWkP6OR:bcklg5x) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/7ed65ce71c12ab6161b77c311b64f07248e706fb/src/components/my-app.js#L230)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

there was no need to remove the 404, was there? But I'm not sure it ever worked
</blockquote></details>

It wasn't working at all, no :smiley: This was an attempt to clean up the code.

**Review by brecke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/3)* status: all files reviewed, 2 unresolved discussions (waiting on @RitaOak)

___
*[src/components/my-app.js, line 230 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/3#-LiJlCqtBtNaQnd9a-Bo:-LiNgLQKEMQFUTuDnScG:bjxxel5) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/7ed65ce71c12ab6161b77c311b64f07248e706fb/src/components/my-app.js#L230)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

It wasn't working at all, no :smiley: This was an attempt to clean up the code.
</blockquote></details>

ok then. Accepted.

**Comment by ROak93** [comment]
___
*[src/components/oae-main.js, line 29 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/3#-LiJm2D28XvZhaHQR4hc:-LiNhvSw6mxdBOSkrlUt:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/13610f1a297a72fc399dfd98b8dc726839489958/src/components/oae-main.js#L29)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

is this really necessary? there is no new behaviour as far as I can tell.
</blockquote></details>

Done.

**Comment by ROak93** [comment]
___
*[src/components/homepage.js, line 21 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/3#-LiJkp1b1lPCv5E3k2hw:-LiNfXkN5LfzEbPGtlr8:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/13610f1a297a72fc399dfd98b8dc726839489958/src/components/homepage.js#L21)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

this is not a good name for a custom element... think of it this way: if we ever need to export this WC to other app, would this be a good tag?

Naming is hard :)
</blockquote></details>

Done.

**Comment by ROak93** [comment]
___
*[src/components/homepage.js, line 21 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/3#-LiJkp1b1lPCv5E3k2hw:-LiNiBsFD4KbLoL3qiA3:bscrssi) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/13610f1a297a72fc399dfd98b8dc726839489958/src/components/homepage.js#L21)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Changed it to "oae-landing-page"

**Review by brecke — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/3#-:-LiNnOpS0NCjt6-L2_zj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by brecke** [comment]
Feel free to merge, @RitaOak :)

**Pull request merged**
