### PR TITLE
Library interface

### PR DESCRIPTION
**Pull request by ROak93**
Found a better way to make the tags section, will do another commit in a few hours.

---
This change is [Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/21)

### CODE REVIEW

**Review by brecke — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/21)* status: all files reviewed, 4 unresolved discussions (waiting on @RitaOak)

___
*[package.json, line 35 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/21#-Lp2Px7dCNptuZZxBlLq:-Lp2Px7e1wEv4jl2UG6r:b-o5q8o8) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/70238e43fc9c2f4009ee30471f6e7a197e1c1860/package.json#L35)):*
> ```
> cool-checkboxes-for-bulma.io
> ```

Are we sure about this? Last published 2 years ago... probably based on a previous bulma version I wonder
___
*[src/components/sidebar.js, line 17 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/21#-Lp2T7RPE44OxChEhWBu:-Lp2T7RQDyu-UR9BLSpb:b-chf8p7) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/70238e43fc9c2f4009ee30471f6e7a197e1c1860/src/components/sidebar.js#L17)):*
> ```JavaScript
>             
>           </a>
>         </div>
> ```

why the bulma logo?
___
*[style/app.scss, line 7 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/21#-Lp2QxuI7uazxwuxfxOw:-Lp2QxuI7uazxwuxfxOx:b-97x51q) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/70238e43fc9c2f4009ee30471f6e7a197e1c1860/style/app.scss#L7)):*
> ```SCSS
> 
> // Import Material Design
> //@import "../node_modules/material-design-icons/iconfont/";
> ```

Are you going to need all these comments?
___
*[style/app.scss, line 449 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/21#-Lp2R1qyCnnlaBi9L-pB:-Lp2R1qyCnnlaBi9L-pC:bvhic4j) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/70238e43fc9c2f4009ee30471f6e7a197e1c1860/style/app.scss#L449)):*
> ```SCSS
> 
> // Library
> // Library Table
> ```

Wait, wait, wait...  why are you creating all this CSS in app.scss?? shouldn't every component have its own scss (as every web component scopes its own css) and then import it? The less global/shared css, the better.

**Comment by ROak93** [comment]
___
*[package.json, line 35 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/21#-Lp2Px7dCNptuZZxBlLq:-Lp3mtBeDlGEChxkihV1:brgtq7s) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/70238e43fc9c2f4009ee30471f6e7a197e1c1860/package.json#L35)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

> ```
> cool-checkboxes-for-bulma.io
> ```

Are we sure about this? Last published 2 years ago... probably based on a previous bulma version I wonder
</blockquote></details>

This extension is part of the official components supported by Bulma. Unfortunately, I was not able to make it work for some reason. It would've been extremely helpful for styling checkboxes.

**Comment by ROak93** [comment]
___
*[src/components/sidebar.js, line 17 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/21#-Lp2T7RPE44OxChEhWBu:-Lp3nLeJ0vjx34CQG-Yq:b3bvsuw) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/70238e43fc9c2f4009ee30471f6e7a197e1c1860/src/components/sidebar.js#L17)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

why the bulma logo?
</blockquote></details>

It's a placeholder for the OAE logo that I was using to position the side menu elements correctly

**Comment by ROak93** [comment]
___
*[style/app.scss, line 7 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/21#-Lp2QxuI7uazxwuxfxOw:-Lp3nlsN8QfspyUYZUql:b-mbq0gn) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/70238e43fc9c2f4009ee30471f6e7a197e1c1860/style/app.scss#L7)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

Are you going to need all these comments?
</blockquote></details>

The Open Sans  I'd say yes, as they make clear what kind of font weights we're using. Material imports can go, I think.

**Comment by ROak93** [comment]
___
*[style/app.scss, line 449 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/21#-Lp2R1qyCnnlaBi9L-pB:-Lp3o3ygBa3rTxjTe0mc:bj89tg4) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/70238e43fc9c2f4009ee30471f6e7a197e1c1860/style/app.scss#L449)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

Wait, wait, wait...  why are you creating all this CSS in app.scss?? shouldn't every component have its own scss (as every web component scopes its own css) and then import it? The less global/shared css, the better.
</blockquote></details>

Will make the changes ASAP

**Comment by ROak93** [comment]
___
*[src/components/sidebar.js, line 17 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/21#-Lp2T7RPE44OxChEhWBu:-Lp3nhpC171TmjqEmnJr:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/70238e43fc9c2f4009ee30471f6e7a197e1c1860/src/components/sidebar.js#L17)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

It's a placeholder for the OAE logo that I was using to position the side menu elements correctly
</blockquote></details>

Done.

**Review by brecke — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/21)* status: all files reviewed, 2 unresolved discussions (waiting on @brecke and @RitaOak)

___
*[package.json, line 35 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/21#-Lp2Px7dCNptuZZxBlLq:-Lp3ylgZ8OrMuqUM9BuW:b-e3his2) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/70238e43fc9c2f4009ee30471f6e7a197e1c1860/package.json#L35)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

This extension is part of the official components supported by Bulma. Unfortunately, I was not able to make it work for some reason. It would've been extremely helpful for styling checkboxes. 
</blockquote></details>

Maybe I can try something?

**Comment by ROak93** [comment]
___
*[package.json, line 35 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/21#-Lp2Px7dCNptuZZxBlLq:-Lp42GeT-4CW2shczUIr:b-ulneo8) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/70238e43fc9c2f4009ee30471f6e7a197e1c1860/package.json#L35)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

Maybe I can try something?
</blockquote></details>

Sure! Go ahead :D

**Review by brecke — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/21)* status: all files reviewed, 2 unresolved discussions (waiting on @brecke and @RitaOak)

___
*[package.json, line 35 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/21#-Lp2Px7dCNptuZZxBlLq:-Lp7eyllAMFApql96CSm:b3n51z9) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/70238e43fc9c2f4009ee30471f6e7a197e1c1860/package.json#L35)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

Sure! Go ahead :D 
</blockquote></details>

Doesn't work because it uses a previous version of bulma. Giving up :)

**Review by ROak93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/21)* status: 3 of 21 files reviewed, 2 unresolved discussions (waiting on @brecke)

___
*[package.json, line 35 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/21#-Lp2Px7dCNptuZZxBlLq:-LpTDpxI3xdn7fDG0hF8:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/70238e43fc9c2f4009ee30471f6e7a197e1c1860/package.json#L35)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

Doesn't work because it uses a previous version of bulma. Giving up :)
</blockquote></details>

Done.

**Review by brecke — DISMISSED** [review]
:lgtm:

> Reviewed 18 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/21#-:-LpTS7G7-ZrfmC__Vr1v:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @RitaOak)

___
*[package.json, line 27 at r3](https://reviewable.io/reviews/oaeproject/biscuit-ux/21#-LpTKrReBpTdYki-bmXT:-LpTKrReBpTdYki-bmXU:b-pzt8tv) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/139125eca2cd6c4af042d216f3018cb0105cd082/package.json#L27)):*
> ```JSON
>   },
>   "dependencies": {
>     "@fortawesome/fontawesome-free": "^5.11.1",
> ```

remove this, I think?

**Comment by ROak93** [comment]
___
*[package.json, line 27 at r3](https://reviewable.io/reviews/oaeproject/biscuit-ux/21#-LpTKrReBpTdYki-bmXT:-LpTq7Y50ELjYpIbWvHK:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/139125eca2cd6c4af042d216f3018cb0105cd082/package.json#L27)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

remove this, I think?
</blockquote></details>

Done.

**Comment by ROak93** [comment]
:lgtm:

**Review by brecke — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/21)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
