### PR TITLE
Interface fixes

### PR DESCRIPTION
**Pull request by ROak93**
This change is [Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/44)

### CODE REVIEW

**Comment by ROak93** [comment]
But we always had a .gitignore. What is this witchcraft?

**Review by brecke — CHANGES_REQUESTED** [review]
Ok, so:

- Remove comments that we no longer need
- Remind me again why we need a bunch of (temporary) V2 files
- Feel free to remove old scaffolding files at will

> Reviewed 20 of 25 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-:-M8K019m-pv0BvRjAseH:bjxxlip)* status: all files reviewed, 5 unresolved discussions (waiting on @RitaOak)

___
*[src/components/shop-products.js, line 13 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-M8K-3XS7_isLm6vFsYz:-M8K-3XS7_isLm6vFsZ-:bgzyiwx) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/e7f0168eafa1ff875bee7d9d5c12d8e18f211f63/src/components/shop-products.js#L13)):*
> ```JavaScript
> /* eslint-disable import/no-unassigned-import */
> 
> class ShopProducts extends PageViewElement {
> ```

why don't you just erase it? this is a file from the project template
___
*[src/components/sidebarV2.js, line 1 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-M8K-ICKEr98XKCXbWLE:-M8K-ICKEr98XKCXbWLF:b-wgzoe2) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/e7f0168eafa1ff875bee7d9d5c12d8e18f211f63/src/components/sidebarV2.js#L1)):*
> ```JavaScript
> import { html, LitElement } from 'lit-element';
> ```

what does V2 mean?
___
*[src/components/top-navV2.js, line 1 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-M8K-SIyADOaYFur5HMi:-M8K-SIyADOaYFur5HMj:bg67990) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/e7f0168eafa1ff875bee7d9d5c12d8e18f211f63/src/components/top-navV2.js#L1)):*
> ```JavaScript
> import { html, LitElement } from 'lit-element';
> ```

Why do we need a V2?
___
*[style/app.scss, line 168 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-M8K-ZCs6Y4BwGEGa__j:-M8K-ZCs6Y4BwGEGa__k:b-8ofrrn) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/e7f0168eafa1ff875bee7d9d5c12d8e18f211f63/style/app.scss#L168)):*
> ```SCSS
> .menu {
>   width: 185px;
>   //position: fixed;
> ```

do we need these comments? and the others above?
___
*[style/topnav-buttons.scss, line 19 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-M8K-xbm1DsuMMHdk_GP:-M8K-xbm1DsuMMHdk_GQ:bhjw12c) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/e7f0168eafa1ff875bee7d9d5c12d8e18f211f63/style/topnav-buttons.scss#L19)):*
> ```SCSS
>   font-size: 14px;
>   height: 35px;
>   //border-radius: 25px;
> ```

do we need these?

**Comment by ROak93** [comment]
___
*[style/app.scss, line 168 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-M8K-ZCs6Y4BwGEGa__j:-M8MBUKI2blDsjap3gZo:b-p3yigg) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/e7f0168eafa1ff875bee7d9d5c12d8e18f211f63/style/app.scss#L168)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

do we need these comments? and the others above?
</blockquote></details>

they're helpers to revert to a previous layout, nothing too important but that should stay for now

**Comment by ROak93** [comment]
___
*[style/topnav-buttons.scss, line 19 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-M8K-xbm1DsuMMHdk_GP:-M8MBtxT5K2Of4W5MTLH:bjquptk) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/e7f0168eafa1ff875bee7d9d5c12d8e18f211f63/style/topnav-buttons.scss#L19)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

do we need these?
</blockquote></details>

same as before

**Comment by ROak93** [comment]
___
*[src/components/shop-products.js, line 13 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-M8K-3XS7_isLm6vFsYz:-M8MBxCt69p6lHhfUFVP:bq1vcf1) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/e7f0168eafa1ff875bee7d9d5c12d8e18f211f63/src/components/shop-products.js#L13)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

why don't you just erase it? this is a file from the project template
</blockquote></details>

I've been trying to delete the shop files, but for some reason they cause the project to send several error messages. It didn't crash, but hours later I still haven't figured out where the problem lies, so I'll just leave those files for now.

**Review by ROak93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/44)* status: all files reviewed, 5 unresolved discussions (waiting on @brecke)

___
*[src/components/sidebarV2.js, line 1 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-M8K-ICKEr98XKCXbWLE:-M8MBCod4z3cG-ZUQWz6:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/e7f0168eafa1ff875bee7d9d5c12d8e18f211f63/src/components/sidebarV2.js#L1)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

what does V2 mean?
</blockquote></details>

Done.
___
*[src/components/top-navV2.js, line 1 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-M8K-SIyADOaYFur5HMi:-M8MBDbb3d52NjYoZc1j:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/e7f0168eafa1ff875bee7d9d5c12d8e18f211f63/src/components/top-navV2.js#L1)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

Why do we need a V2?
</blockquote></details>

Done.

**Review by brecke — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/44)* status: all files reviewed, 2 unresolved discussions (waiting on @RitaOak)

___
*[src/components/shop-products.js, line 13 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-M8K-3XS7_isLm6vFsYz:-M8MXITC4_5Rx7abNwmz:b-moge94) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/e7f0168eafa1ff875bee7d9d5c12d8e18f211f63/src/components/shop-products.js#L13)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

I've been trying to delete the shop files, but for some reason they cause the project to send several error messages. It didn't crash, but hours later I still haven't figured out where the problem lies, so I'll just leave those files for now.
</blockquote></details>

lol ok
create an issue for that on github if you please
___
*[style/app.scss, line 168 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-M8K-ZCs6Y4BwGEGa__j:-M8MXTFrBJgH8t-vlXo7:b-geg0ba) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/e7f0168eafa1ff875bee7d9d5c12d8e18f211f63/style/app.scss#L168)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

they're helpers to revert to a previous layout, nothing too important but that should stay for now
</blockquote></details>

then expand the comment to say that explicitly. Even you won't know what they're for in a year otherwise :)
___
*[style/topnav-buttons.scss, line 19 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-M8K-xbm1DsuMMHdk_GP:-M8MXiq_Ao6rS1n9pn_2:btxl8nj) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/e7f0168eafa1ff875bee7d9d5c12d8e18f211f63/style/topnav-buttons.scss#L19)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

same as before
</blockquote></details>

do as I suggested then

**Review by ROak93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/44)* status: all files reviewed, 2 unresolved discussions (waiting on @brecke)

___
*[style/app.scss, line 168 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-M8K-ZCs6Y4BwGEGa__j:-M8NU6WX3EJoONo7DeRg:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/e7f0168eafa1ff875bee7d9d5c12d8e18f211f63/style/app.scss#L168)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

then expand the comment to say that explicitly. Even you won't know what they're for in a year otherwise :)
</blockquote></details>

Done.
___
*[style/topnav-buttons.scss, line 19 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-M8K-xbm1DsuMMHdk_GP:-M8NUhGhBCXVyjZ7HndW:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/e7f0168eafa1ff875bee7d9d5c12d8e18f211f63/style/topnav-buttons.scss#L19)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

do as I suggested then
</blockquote></details>

Done.

**Review by brecke — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/44#-:-M8PE_5ACRuXmW-2aZRW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
