### PR TITLE
Interface updates

### PR DESCRIPTION
**Pull request by ROak93**
Missing (homepage):
1. div 100% height
2. login button 
3. animations for svg's

---
This change is [Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/24)

### CODE REVIEW

**Review by brecke — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-:-Lr8Q0Y68v7QXjW6U7Sg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by brecke — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-:-LrIjkLl5VpyVwXXwRhq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by brecke — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/24)* status: all files reviewed, 1 unresolved discussion (waiting on @RitaOak)

___
*[src/components/oae.js, line 18 at r3](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-LriqTLz4vHpQN81Grc6:-LriqTLz4vHpQN81Grc7:bk4aa4v) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/1c6c2f50c1ab5d1a271983eaaa3e2ada9739ccc4/src/components/oae.js#L18)):*
> ```JavaScript
> import sharedStyles from '../../style/app.scss';
> import landingStyles from '../../style/landing-page.scss';
> import homeV2Styles from '../../style/homepage-v2.scss';
> ```

v2?? is this a good idea?

**Review by brecke — COMMENTED** [review]
not sure what the v2 is all about but otherwise it all looks ok

> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-:-LrrgU2P2gcXh3GK_HGJ:b-8bb30l)* status: all files reviewed, 1 unresolved discussion (waiting on @RitaOak)

**Comment by ROak93** [comment]
___
*[src/components/oae.js, line 18 at r3](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-LriqTLz4vHpQN81Grc6:-LsH25qaAa5uqRv0hIaO:b553c5a) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/1c6c2f50c1ab5d1a271983eaaa3e2ada9739ccc4/src/components/oae.js#L18)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

v2?? is this a good idea?
</blockquote></details>

This change will be included as: alternate templates for institutions to choose (homepage)

**Comment by ROak93** [comment]
:lgtm:

**Review by brecke — DISMISSED** [review]
:lgtm:

> Reviewed 12 of 12 files at r5, 3 of 7 files at r6, 21 of 21 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-:-Lt13QmU0l6Rb2N8EEYa:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @RitaOak)

___
*[images/background.jpg.xmp, line 1 at r7](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-Lt13HHUBYxrtDLkxxuw:-Lt13HHV8LDIHgo0XBXN:b-aflr8e) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/92a7cbc29984170ef49f165ed4d4cd84b9320bf1/images/background.jpg.xmp#L1)):*
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> ```

what is this?
___
*[images/background_01.jpg, line 0 at r7](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-Lt0wXWz0h-0GKaABgDj:-Lt0wXWz0h-0GKaABgDk:bxv3kfk) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/92a7cbc29984170ef49f165ed4d4cd84b9320bf1/images/background_01.jpg#L0)):*
a bit too large, isnt it?
___
*[images/background_02.jpg, line 0 at r7](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-Lt0wcizAvhNyIVN5Tv8:-Lt0wcizAvhNyIVN5Tv9:b-142b6l) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/92a7cbc29984170ef49f165ed4d4cd84b9320bf1/images/background_02.jpg#L0)):*
and this! can we make these smaller?

**Comment by ROak93** [comment]
___
*[images/background.jpg.xmp, line 1 at r7](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-Lt13HHUBYxrtDLkxxuw:-Lt5tsfa1IM5cTcFOPu6:b-luensn) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/92a7cbc29984170ef49f165ed4d4cd84b9320bf1/images/background.jpg.xmp#L1)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

what is this?
</blockquote></details>

That the Unicode Standard that allows the interface to show and support symbols like "ç", among others. It's necessary given that the majority of our users are French

**Comment by ROak93** [comment]
___
*[images/background_01.jpg, line  at r7](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-Lt0wXWz0h-0GKaABgDj:-Lt5v53-Eb34aFAznIxo:bfeh4su) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/92a7cbc29984170ef49f165ed4d4cd84b9320bf1/images/background_01.jpg#L)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

a bit too large, isnt it?
</blockquote></details>

Usually 8-10MB is the max supported size for image uploads, so we're actually within range! For the frontend, we'll need to restrict the file size, though.

**Comment by ROak93** [comment]
___
*[images/background_02.jpg, line  at r7](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-Lt0wcizAvhNyIVN5Tv8:-Lt5vSEjBcBisjChkC8n:behbg3z) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/92a7cbc29984170ef49f165ed4d4cd84b9320bf1/images/background_02.jpg#L)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

and this! can we make these smaller?
</blockquote></details>

As explained above, we are very much within range ^^

**Review by ROak93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/24)* status: 31 of 33 files reviewed, 3 unresolved discussions (waiting on @brecke)

___
*[images/background.jpg.xmp, line 1 at r7](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-Lt13HHUBYxrtDLkxxuw:-LtBLIzZ0okMs3Vq1CZp:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/92a7cbc29984170ef49f165ed4d4cd84b9320bf1/images/background.jpg.xmp#L1)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

That the Unicode Standard that allows the interface to show and support symbols like "ç", among others. It's necessary given that the majority of our users are French
</blockquote></details>

Done.
___
*[images/background_01.jpg, line  at r7](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-Lt0wXWz0h-0GKaABgDj:-LtBLKDW-plk2lpK9Nyp:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/92a7cbc29984170ef49f165ed4d4cd84b9320bf1/images/background_01.jpg#L)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

Usually 8-10MB is the max supported size for image uploads, so we're actually within range! For the frontend, we'll need to restrict the file size, though.
</blockquote></details>

Done.
___
*[images/background_02.jpg, line  at r7](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-Lt0wcizAvhNyIVN5Tv8:-LtBLL6y5LrkVTv_O-Z-:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/92a7cbc29984170ef49f165ed4d4cd84b9320bf1/images/background_02.jpg#L)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

As explained above, we are very much within range ^^
</blockquote></details>

Done.

**Review by brecke — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, 5 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-:-LtV8lssDiMWkrshoz25:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[images/background_01.jpg, line  at r7](https://reviewable.io/reviews/oaeproject/biscuit-ux/24#-Lt0wXWz0h-0GKaABgDj:-LtQeZ4F3c7obQpbSr_9:b-6krpdd) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/92a7cbc29984170ef49f165ed4d4cd84b9320bf1/images/background_01.jpg#L)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

we will.

**Pull request merged**
