### PR TITLE
Dashboard interface

### PR DESCRIPTION
**Pull request by ROak93**
This change is [Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/18)

### CODE REVIEW

**Review by brecke — CHANGES_REQUESTED** [review]
Just minor stuff all around. However two things must be fixed:
- node_modules local paths should be removed
- singular custom elements

Let's go!

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-:-Llk7kVh8bJ6vlPIL9Le:b-ubqocn)* status: all files reviewed, 13 unresolved discussions (waiting on @RitaOak)

___
*[index.html, line 35 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk5Fer562551bkz8S3:-Llk5Fer562551bkz8S4:b-jywmr9) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/index.html#L35)):*
> ```HTML
>     <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
>       rel="stylesheet">
>     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
> ```

Sorry I am noob again at this point: is this necessary? aren't we importing bulma sass components and then having them compiled through webpack? I thought we didn't need this. I might be utterly wrong.
___
*[index.html, line 36 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk5CBF5DlEdrdoadDc:-Llk5CBF5DlEdrdoadDd:b-bv3z6z) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/index.html#L36)):*
> ```
> https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
> ```

Is this a CDN link?
___
*[src/components/breadcrumbs.js, line 5 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7YKz9SkSuV7lQdT2:-Llk7YKz9SkSuV7lQdT3:b-qgqztw) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/breadcrumbs.js#L5)):*
> ```JavaScript
> import sharedStyles from '../../style/app.scss';
> 
> class breadCrumbs extends LitElement {
> ```

singular
___
*[src/components/dashboard.js, line 40 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7dV68DXJozicYQ8b:-Llk7dV68DXJozicYQ8c:b-n4jkoo) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/dashboard.js#L40)):*
> ```JavaScript
>                         <section class="is-flex">
>                           <span class="icon tag-activity-dashboard">
>                             
> ```

this again, we must find a workaround
___
*[src/components/info-cards.js, line 5 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk5i7S2bddtIrsa_bu:-Llk5i7T6AxPox7cAgJf:b-sqzfrx) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/info-cards.js#L5)):*
> ```JavaScript
> import sharedStyles from '../../style/app.scss';
> 
> class infoCards extends LitElement {
> ```

I would name it using the singular, as it's just ONE custom element that you can use many times.
___
*[src/components/news-feed.js, line 19 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk6Bki8WO9L_o4-IFu:-Llk66Ox9fYdSNTvZHWO:b-gpxs5q) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/news-feed.js#L19)):*
> ```
> s
> ```

silly question, shouldn't this be a separate component? we might want to use this <avatar> kind of thing somewhere else. Of course we don't have to do it now but let's just think about it
___
*[src/components/tag-cards.js, line 6 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk6Y1E9CrD9LQYi875:-Llk6Y1E9CrD9LQYi876:bxu8l8i) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/tag-cards.js#L6)):*
> ```JavaScript
> import './tags.js';
> 
> class tagCards extends LitElement {
> ```

singular here as well, so we can use <tar-card> not <tag-cards>
___
*[src/components/tags.js, line 5 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk6nooAHICR1mvYqKj:-Llk6nooAHICR1mvYqKk:b-x7v9fj) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/tags.js#L5)):*
> ```JavaScript
> import sharedStyles from '../../style/app.scss';
> 
> class tagsButton extends LitElement {
> ```

<tag-button> ?
___
*[src/components/tags.js, line 16 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk6s4B9ujE0w6TnCzq:-Llk6s4B9ujE0w6TnCzr:b11xfj) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/tags.js#L16)):*
> ```JavaScript
>           <a class="button is-small is-rounded tag-button-colors">
>             <span class="icon tag-icons">
>               
> ```

is this really how it's supposed to work? this is not very elegant, and also very unsafe because we're telling the outside world what paths we're using. There must be a better way.
___
*[style/app.scss, line 140 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7BqoCcRI7FNcBXBE:-Llk7BqoCcRI7FNcBXBF:bwg75k7) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/style/app.scss#L140)):*
> ```SCSS
> }
> 
> //Side Menu
> ```

surprised to see this, linting should take care of adding a space between // and text
___
*[style/app.scss, line 227 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7JHr6xfvEmzqxgCR:-Llk7JHr6xfvEmzqxgCS:b-2guby3) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/style/app.scss#L227)):*
> ```SCSS
> }
> 
> //Navbar
> ```

same here
___
*[style/app.scss, line 272 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7KP2EncFlDZOh6EB:-Llk7KP2EncFlDZOh6EC:bji28bi) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/style/app.scss#L272)):*
> ```SCSS
> }
> 
> //Cards
> ```

and here
___
*[style/app.scss, line 337 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7M0E81GErsFUiN13:-Llk7M0E81GErsFUiN14:b-az44f6) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/style/app.scss#L337)):*
> ```SCSS
> }
> 
> //Tags
> ```

....and here

**Comment by ROak93** [comment]
___
*[src/components/dashboard.js, line 40 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7dV68DXJozicYQ8b:-Llm04MNBVpgEO2ZFYA5:bmlfkmx) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/dashboard.js#L40)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

this again, we must find a workaround
</blockquote></details>

We really must, as Bulma supposedly lets you use classes to include icons (and change colours quite easily). I can't seem to make it work just yet, though.

**Comment by ROak93** [comment]
___
*[src/components/news-feed.js, line 19 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk6Bki8WO9L_o4-IFu:-Llm0QJy6kcMFSh-Zpnm:bdb8ub5) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/news-feed.js#L19)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

> ```
> s
> ```

silly question, shouldn't this be a separate component? we might want to use this <avatar> kind of thing somewhere else. Of course we don't have to do it now but let's just think about it
</blockquote></details>

This is just the structure for the news feed card. Right now, we only need it for this component ^^

**Comment by ROak93** [comment]
___
*[src/components/tags.js, line 5 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk6nooAHICR1mvYqKj:-Llm0g_j5CNOgAx2Av9V:b-lbi0p5) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/tags.js#L5)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

<tag-button> ?
</blockquote></details>

The card for the tags is different than the tags themselves. The tagCard is the container for the user's latest tags.

**Comment by ROak93** [comment]
___
*[style/app.scss, line 140 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7BqoCcRI7FNcBXBE:-Llm11MN6FvVNO_CSmUM:b-x51h0e) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/style/app.scss#L140)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

surprised to see this, linting should take care of adding a space between // and text
</blockquote></details>

Tried it quite a few times, it doesn't care about scss comments.

**Review by ROak93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/18)* status: 7 of 15 files reviewed, 13 unresolved discussions (waiting on @brecke)

___
*[index.html, line 35 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk5Fer562551bkz8S3:-Llm00402YsuXEnWljHL:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/index.html#L35)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

Sorry I am noob again at this point: is this necessary? aren't we importing bulma sass components and then having them compiled through webpack? I thought we didn't need this. I might be utterly wrong.
</blockquote></details>

Done.
___
*[index.html, line 36 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk5CBF5DlEdrdoadDc:-Llm00fK7QMzGldJNfwc:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/index.html#L36)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

> ```
> https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
> ```

Is this a CDN link?
</blockquote></details>

Done.
___
*[src/components/dashboard.js, line 40 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7dV68DXJozicYQ8b:-Llm0KWb0hpCALzlhXht:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/dashboard.js#L40)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

We really must, as Bulma supposedly lets you use classes to include icons (and change colours quite easily). I can't seem to make it work just yet, though.
</blockquote></details>

Done.
___
*[src/components/news-feed.js, line 19 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk6Bki8WO9L_o4-IFu:-Llm0d0HAI0zDa4nW_1c:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/news-feed.js#L19)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

This is just the structure for the news feed card. Right now, we only need it for this component ^^ 
</blockquote></details>

Done.
___
*[src/components/tags.js, line 5 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk6nooAHICR1mvYqKj:-Llm0uRDBCL8uffAgaLL:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/tags.js#L5)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

The card for the tags is different than the tags themselves. The tagCard is the container for the user's latest tags. 
</blockquote></details>

Done.
___
*[src/components/tags.js, line 16 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk6s4B9ujE0w6TnCzq:-Llm0xExBRtyThJ2KNos:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/tags.js#L16)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

is this really how it's supposed to work? this is not very elegant, and also very unsafe because we're telling the outside world what paths we're using. There must be a better way.
</blockquote></details>

Done.
___
*[style/app.scss, line 140 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7BqoCcRI7FNcBXBE:-Llm1H1oE33OPeXWYJ5s:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/style/app.scss#L140)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

Tried it quite a few times, it doesn't care about scss comments.
</blockquote></details>

Done.
___
*[style/app.scss, line 227 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7JHr6xfvEmzqxgCR:-Llm1HWA9p2_cTkauF0Q:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/style/app.scss#L227)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[style/app.scss, line 272 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7KP2EncFlDZOh6EB:-Llm1HxfEbCGXbuCVv88:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/style/app.scss#L272)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

and here
</blockquote></details>

Done.
___
*[style/app.scss, line 337 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7M0E81GErsFUiN13:-Llm1IkR1yzwtGHP7-Fs:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/style/app.scss#L337)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

....and here
</blockquote></details>

Done.
___
*[src/components/breadcrumbs.js, line 5 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7YKz9SkSuV7lQdT2:-Llm02Og0Ai9IbGB-4ZL:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/breadcrumbs.js#L5)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

singular
</blockquote></details>

Done.
___
*[src/components/info-cards.js, line 5 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk5i7S2bddtIrsa_bu:-Llm0MH8-UUow_Dvjczy:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/info-cards.js#L5)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

I would name it using the singular, as it's just ONE custom element that you can use many times.
</blockquote></details>

Done.
___
*[src/components/tag-cards.js, line 6 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk6Y1E9CrD9LQYi875:-Llm0eYY1HRnRGVfaIO0:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/tag-cards.js#L6)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

singular here as well, so we can use <tar-card> not <tag-cards>
</blockquote></details>

Done.

**Review by brecke — CHANGES_REQUESTED** [review]
the url thing is still missing, but we're making progress!

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-:-LlpMzxPCA1o6BvezYQt:b-3p5rij)* status: all files reviewed, 5 unresolved discussions (waiting on @RitaOak)

___
*[index.html, line 36 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk5CBF5DlEdrdoadDc:-LlpMPLvDzQqhhDt2w56:bm7sao7) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/index.html#L36)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

what was done? removed it? and where is it now?
___
*[src/components/dashboard.js, line 40 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7dV68DXJozicYQ8b:-LlpM_qMAlOtcHcswFhx:b-8vszhd) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/dashboard.js#L40)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

what is? the path is still there o_O
___
*[src/components/tags.js, line 5 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk6nooAHICR1mvYqKj:-LlpN7lvEK5wIqc6QUff:bc6l9hs) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/tags.js#L5)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

TagButton then? not tagsButton?
___
*[src/components/tags.js, line 16 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk6s4B9ujE0w6TnCzq:-LlpNDkMBXXmlndvt1yO:b-il4pwk) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/tags.js#L16)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

what is? It's still there!
___
*[style/app.scss, line 140 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7BqoCcRI7FNcBXBE:-LlpMqr86T4ScGFL8rRW:bv9yn0r) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/style/app.scss#L140)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

then manually it is, without the space it looks awful

**Comment by ROak93** [comment]
___
*[index.html, line 36 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk5CBF5DlEdrdoadDc:-LlpuELtE35Gx8V7eoyX:b9hq4s2) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/index.html#L36)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

what was done? removed it? and where is it now?
</blockquote></details>

It was removed because we don't need it. We want to use the MD icons instead.

**Comment by ROak93** [comment]
___
*[src/components/tags.js, line 5 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk6nooAHICR1mvYqKj:-Llpwq0r5cIPhUvJ41_8:bajkh2t) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/tags.js#L5)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

TagButton then? not tagsButton?
</blockquote></details>

tagButton is more specific as it is the button for one tag.

**Comment by ROak93** [comment]
___
*[src/components/tags.js, line 16 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk6s4B9ujE0w6TnCzq:-Llpx0AG6aRb8om5dE4x:btgvgid) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/tags.js#L16)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

what is? It's still there!
</blockquote></details>

The situation is acknowledged, I just haven't been able to fix it just yet.

**Comment by ROak93** [comment]
___
*[src/components/dashboard.js, line 40 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7dV68DXJozicYQ8b:-LlpxDTJ6oYaXKGMJdwu:b-9xo9kn) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/dashboard.js#L40)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

what is? the path is still there o_O
</blockquote></details>

The code is stubborn :100: But the situation has been acknowledged ^^

**Review by brecke — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/18)* status: all files reviewed, 3 unresolved discussions (waiting on @RitaOak)

___
*[src/components/dashboard.js, line 40 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk7dV68DXJozicYQ8b:-Lm3wZ-Z7_6GbYJJrLIG:b-m2813x) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/dashboard.js#L40)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

The code is stubborn :100: But the situation has been acknowledged ^^
</blockquote></details>

I wasn't able to fix this 100% but I did see this, and it seems to be more elegant even though it is not a  per se. What do you think? 


___
*[src/components/tags.js, line 5 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk6nooAHICR1mvYqKj:-Lm3utcVCtPswafatean:b51yos3) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/tags.js#L5)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

tagButton is more specific as it is the button for one tag.
</blockquote></details>

yet it hasn't been renamed, nor the filename which must match the classname
___
*[src/components/tags.js, line 16 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-Llk6s4B9ujE0w6TnCzq:-Lm3wowSDcf-Z6IPrAAP:b-n3wh94) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/98a22d3ad148f5b7071fdb565326f5ef4f1f6ff0/src/components/tags.js#L16)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

The situation is acknowledged, I just haven't been able to fix it just yet.
</blockquote></details>

See above, maybe if using the package by importing the scss module would work? instead of using the URL specifically.

**Review by brecke — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/18#-:-Lm4rlYN4ODiiU1MCT5Z:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @RitaOak)

**Pull request merged**
