### PR TITLE
Interface updatesv2

### PR DESCRIPTION
**Pull request by ROak93**
This change is [Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/27)

### CODE REVIEW

**Review by brecke — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/27)* status: all files reviewed, 2 unresolved discussions (waiting on @RitaOak)

___
*[images/user.jpg, line 0 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/27#-Lvji_yP7eLvAWYK9xPK:-Lvji_yQ2uT1iGNR9LAQ:b-ck3jw9) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/ec5ad8f894982c51058bf71f72b5d4049507b110/images/user.jpg#L0)):*
I think we should do something about the image filesizes. Let's create a github issue on Biscuit-ux to deal with this sometime at a later stage, shall we? I'm guessing there are ways to deal with this, just not sure which ones.
___
*[style/topnav-buttons.scss, line 25 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/27#-LvjjQgk22ZjLFCd81w1:-LvjjQgk22ZjLFCd81w2:ba805zf) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/ec5ad8f894982c51058bf71f72b5d4049507b110/style/topnav-buttons.scss#L25)):*
> ```SCSS
> 
> .notification-icon {
>   color: black;
> ```

A longe time ago I read the following: https://ianstormtaylor.com/design-tip-never-use-black/

What do you make of this?

**Review by brecke — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/27)* status: all files reviewed, 3 unresolved discussions (waiting on @RitaOak)

___
*[style/news-feed.scss, line 5 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/27#-LwK8unM2gXN1DtlTmhT:-LwK8unM2gXN1DtlTmhU:bd8itbg) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/9849b0fe5e02a88dbbfad008330876937b546405/style/news-feed.scss#L5)):*
> ```SCSS
>   box-shadow: none;
>   background-color: white;
>   //box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
> ```

why the comment?

**Comment by ROak93** [comment]
___
*[images/user.jpg, line  at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/27#-Lvji_yP7eLvAWYK9xPK:-LwO6zGAB74Di0zVh0eE:b-b5xx67) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/ec5ad8f894982c51058bf71f72b5d4049507b110/images/user.jpg#L)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

I think we should do something about the image filesizes. Let's create a github issue on Biscuit-ux to deal with this sometime at a later stage, shall we? I'm guessing there are ways to deal with this, just not sure which ones.
</blockquote></details>

Issue created. Tagged you

**Comment by ROak93** [comment]
___
*[style/news-feed.scss, line 5 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/27#-LwK8unM2gXN1DtlTmhT:-LwO76Kr5RDEQSHN7HTq:ba4wj6) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/9849b0fe5e02a88dbbfad008330876937b546405/style/news-feed.scss#L5)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

why the comment?
</blockquote></details>

experimenting with something, will remove in due time

**Comment by ROak93** [comment]
___
*[style/topnav-buttons.scss, line 25 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/27#-LvjjQgk22ZjLFCd81w1:-LwO7Cmt5BNYA380jPMC:bbiv7q1) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/ec5ad8f894982c51058bf71f72b5d4049507b110/style/topnav-buttons.scss#L25)):*
<details><summary><i>Previously, brecke (Miguel Laginha) wrote…</i></summary><blockquote>

A longe time ago I read the following: https://ianstormtaylor.com/design-tip-never-use-black/

What do you make of this?
</blockquote></details>

Pure black is bad for contrast (which affects accessibility). At this point I was experimenting to check how the overall interface would respond to a brutal change from saturated black to 100% black, but meanwhile I've normalized the colours.

**Review by ROak93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/27)* status: 12 of 14 files reviewed, 3 unresolved discussions (waiting on @brecke)

___
*[images/user.jpg, line  at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/27#-Lvji_yP7eLvAWYK9xPK:-LwO7ixj5-8pefIoVDyM:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/ec5ad8f894982c51058bf71f72b5d4049507b110/images/user.jpg#L)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

Issue created. Tagged you
</blockquote></details>

Done.
___
*[style/news-feed.scss, line 5 at r2](https://reviewable.io/reviews/oaeproject/biscuit-ux/27#-LwK8unM2gXN1DtlTmhT:-LwO7kGp4kvZ8PEiu5NG:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/9849b0fe5e02a88dbbfad008330876937b546405/style/news-feed.scss#L5)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

experimenting with something, will remove in due time
</blockquote></details>

Done.
___
*[style/topnav-buttons.scss, line 25 at r1](https://reviewable.io/reviews/oaeproject/biscuit-ux/27#-LvjjQgk22ZjLFCd81w1:-LwO7lHf-g98CBJ4-RWU:b-896fix) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/ec5ad8f894982c51058bf71f72b5d4049507b110/style/topnav-buttons.scss#L25)):*
<details><summary><i>Previously, RitaOak (Rita Oak) wrote…</i></summary><blockquote>

Pure black is bad for contrast (which affects accessibility). At this point I was experimenting to check how the overall interface would respond to a brutal change from saturated black to 100% black, but meanwhile I've normalized the colours.
</blockquote></details>

Done.

**Review by brecke — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oaeproject/biscuit-ux/27#-:-LwOLyWs4qXrEV3D8byA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @RitaOak)

___
*[src/components/dashboard.js, line 4 at r3](https://reviewable.io/reviews/oaeproject/biscuit-ux/27#-LwOLlq-CJkzwRsUF_Rr:-LwOLlq-CJkzwRsUF_Rs:b-8e03a9) ([raw file](https://github.com/oaeproject/biscuit-ux/blob/c35220d11a6203fb4b600f15f10ad7f4dd70e6dc/src/components/dashboard.js#L4)):*
> ```JavaScript
> import sharedStyles from '../../style/app.scss';
> import dashboardStyles from '../../style/dashboard.scss';
> import dashboardButtonsStyles from '../../style/dashboard-filter.scss';
> ```

why separate styles for buttons and the rest?

**Pull request merged**
